### ISSUE TITLE
Run model on GPU decoded output 

### ISSUE THREAD

**Issue by jiashenC** [NVIDIA/VideoProcessingFramework#127]
I try to prototype running ML inference on decoded output in GPU directly. Is below the correct way to do it?   
```python
    import PyNvCodec as nvc
    import PytorchNvCodec as pnvc

    import torch
    import torchvision

    device = torch.device('cuda')

    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(
        pretrained=True)
    model.float()
    model.to(device)
    model.eval()

    gpuID = 0

    nvDec = nvc.PyNvDecoder('path_to_video_file', gpuID)
    to_rgb = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvc.PixelFormat.NV12, nvc.PixelFormat.RGB, gpuID)
    to_planar = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvc.PixelFormat.RGB, nvc.PixelFormat.RGB_PLANAR, gpuID)

    while True:
        rawSurface = nvDec.DecodeSingleSurface()
        if (rawSurface.Empty()):
            break
        rgb_byte = to_rgb.Execute(rawSurface)
        rgb_planar = to_planar.Execute(rgb_byte)
        surfPlane = rgb_planar.PlanePtr()
        surface_tensor = pnvc.makefromDevicePtrUint8(surfPlane.GpuMem(), surfPlane.Width(), surfPlane.Height(), surfPlane.Pitch(), surfPlane.ElemSize())
        surface_tensor.resize_(3, target_h, target_w)
        surface_tensor = surface_tensor.type(dtype=torch.cuda.FloatTensor)

        # do inference here
        model(surface_tensor)
```

I am getting some errors from the last line.
```
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by niaoyu** [comment]
The model input should be NCHW while CHW in your code.
Just modify,
  surface_tensor.resize_(3, target_h, target_w)
=》
  surface_tensor.resize_(1, 3, target_h, target_w)

**Comment by jiashenC** [comment]
Thanks, this fixes the issue.
