### ISSUE TITLE
CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by SubMarineas** [NVIDIA/VideoProcessingFramework#147]
When I did a local video test, there was no problem, but when I added two or more videos, it told me cuda error address, why?

```python
Traceback (most recent call last):
  File "xxxx.py", line 467, in produce_frame
    rawSurface = nvDec.DecodeSingleSurface()
RuntimeError: /VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:201
CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS
an illegal memory access was encountered
```

**Comment by SubMarineas** [comment]
My installed version is
Video_Codec_SDK_11.0.10,
Ubuntu 18.04,
cuda 10.2,
The rest are the latest version, I am testing how many channels of local mp4 video can be supported by a process instead of rtsp

**Comment by SubMarineas** [comment]
Oh, I found the problem, it seems that my torch and VPF graphics card use do not match, I only run VPF is no problem, but it is very strange...
