### ISSUE TITLE
SampleEncode.py "Older presets(default-lossless_hp) are not supported with NV_ENC_RC_PARAMS

### ISSUE THREAD

**Issue by TheMasterFX** [NVIDIA/VideoProcessingFramework#87]
**Describe the bug**
After compiling successfully the VPF for Python I get the following error when I try the SampeEncode.py example with commandline "python .\SampleEncode.py 0 bla.mkv blubb.mov 1920 1080"

```
Encoding on GPU 0
Traceback (most recent call last):
  File ".\SampleEncode.py", line 82, in <module>
    encode(gpuID, decFilePath, encFilePath, width, heihgt)
  File ".\SampleEncode.py", line 52, in encode
    success = nvEnc.EncodeSingleFrame(rawFrame, encFrame, sync = False)
RuntimeError: NvEncoder::CreateEncoder : m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 8
Description: Older presets(default-lossless_hp) are not supported with NV_ENC_RC_PARAMS::multiPass and/or NV_ENC_INITIALIZE_PARAMS::tuningInfo

 at H:\Python\VideoProcessingFramework\PyNvCodec\TC\src\NvEncoder.cpp:243

H:\Python\VideoProcessingFramework\PyNvCodec\src\PyNvCodec.cpp:128
CUDA error with code 4
No error string available

```
I also tried the example from the Nvidia Homepage https://developer.nvidia.com/blog/vpf-hardware-accelerated-video-processing-framework-in-python/
Then I get the Error:
```
Decoding on GPU 0
Encoding on GPU 0
Traceback (most recent call last):
  File "h:/Python/VideoProcessingFramework/bin/BlubbTest.py", line 14, in <module>
    if not (rawSurface.GetCudaDevicePtr()):
AttributeError: 'PyNvCodec.Surface' object has no attribute 'GetCudaDevicePtr'
H:\Python\VideoProcessingFramework\PyNvCodec\src\PyNvCodec.cpp:128
CUDA error with code 4
No error string available
```
**To Reproduce**
Compile as described in the Wiki using CUDA SDK 11.0 , Video_Codec_SDK_10.0.26 and ffmpeg4.3.1
Cmake-Line:
`H:\Python\VideoProcessingFramework\build>cmake .. -G"Visual Studio 15 2017 Win64" -DFFMPEG_DIR:PATH="H:\Source\ffmpeg-4.3.1-win64-dev" -DVIDEO_CODEC_SDK_DIR:PATH="H:\Source\Video_Codec_SDK_10.0.26" -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DGENERATE_PYTORCH_EXTENSION:BOOL="0" -DCMAKE_INSTALL_PREFIX:PATH="H:\Python\VideoProcessingFramework"`
Got no errors.  Then Compile in VS Studio 15 => No errors.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903, 64 Bit
 - Nvidia driver version: 451.48
 - CUDA Version 11
 - Video Codec SDK Version 10.0.26
 - Python Version 3.7.7

**Comment by rarzumanyan** [comment]
Hi @TheMasterFX 

Thanks for reporting, this is a bug which was introduced at branches merge stage.
The quick workaround is to used new P1...P7 presets like this:
```python
nvEnc = nvc.PyNvEncoder({'preset': 'P4', 'codec': 'h264', 's': res, 'bitrate' : '10M'}, gpuID)
```

Meanwhile I will fix this.

**Comment by TheMasterFX** [comment]
Hi,
that seems to work now. Thanks for the fast fix.

What about the "GetCudaDevicePtr"? (Sorry for putting two problems in this issue)

**Comment by rarzumanyan** [comment]
>What about the "GetCudaDevicePtr"?

`Surface::PlanePtr()` and other similar methods literally return `CUdeviceptr`of the memory object, allocated on the GPU.
It's done to simplify the handshake between VPF and other CUDA-enabled projects (e. g. Pytorch).
Since `CUdeviceptr` is basically uint64_t one can pass it by value across the C++ / Python call stack.

**Comment by TheMasterFX** [comment]
Oh sorry, maybe I was not precise enough.
The call "if not (rawSurface.GetCudaDevicePtr()):" in the example doesn't work.
I get the error:

```
Traceback (most recent call last):
  File "h:/Python/VideoProcessingFramework/bin/BlubbTest.py", line 14, in <module>
    if not (rawSurface.GetCudaDevicePtr()):
AttributeError: 'PyNvCodec.Surface' object has no attribute 'GetCudaDevicePtr'
H:\Python\VideoProcessingFramework\PyNvCodec\src\PyNvCodec.cpp:128
```
What do I have to change to make it work?

**Comment by rarzumanyan** [comment]
@TheMasterFX 

I'm not sure where did you find the `GetCudaDevicePtr()` method. It's not declared as a part of VPF API. 

There are `Surface::PlanePtr` and `SurfacePlane::GpuMem` methods:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ae4608337b80444b50db4a3863498bcf4553d683/PyNvCodec/src/PyNvCodec.cpp#L817
https://github.com/NVIDIA/VideoProcessingFramework/blob/ae4608337b80444b50db4a3863498bcf4553d683/PyNvCodec/src/PyNvCodec.cpp#L838


Using which you can obtain `CUdeviceptr` of underlying CUDA memory as it's shown in [wiki](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Exporting-video-frame-to-Pytorch-tensor) page:
```python
# Create torch tensor from it and reshape because
# pnvc.makefromDevicePtrUint8 creates just a chunk of CUDA memory
# and then copies data from plane pointer to allocated chunk;
surfPlane = rgb_planar.PlanePtr()
surface_tensor = pnvc.makefromDevicePtrUint8(surfPlane.GpuMem(), surfPlane.Width(), surfPlane.Height(), surfPlane.Pitch(), surfPlane.ElemSize())
surface_tensor.resize_(3, target_h, target_w)
```

P. S.
VPF Python API is defined by the bindings between C++ implementation and Python. It's declared starting at
https://github.com/NVIDIA/VideoProcessingFramework/blob/ae4608337b80444b50db4a3863498bcf4553d683/PyNvCodec/src/PyNvCodec.cpp#L792

**Comment by TheMasterFX** [comment]
Perfect! Thanks for the explanation. So the blog post which uses GetCudaDevicePtr ( https://developer.nvidia.com/blog/vpf-hardware-accelerated-video-processing-framework-in-python/ ) is 8 month old and obviously outdated.

**Comment by QuantScientist** [comment]
I saw this and read everything here. This example:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ae4608337b80444b50db4a3863498bcf4553d683/PytorchNvCodec/src/PytorchNvCodec.cpp#L66

Does not depict how to run this on a Video file. Is there such a test or should I explore it myself as you suggested?

**Comment by rarzumanyan** [comment]
Hi Shlomo,

> Is there such a test
Unfortunately no.
PytorchNvCodec sub-project was always built as Pytorch extension.
Though it’s possible to reuse the sources from PytorchNvCodec.cpp and SampleDecode.cpp like this:

#include "PyNvCodec.hpp"
#include <fstream>
#include <iostream>
#include <sstream>

using namespace std;

torch::Tensor makefromDevicePtrUint8(CUdeviceptr ptr, uint32_t width,
                                     uint32_t height, uint32_t pitch,
                                     uint32_t elem_size_bytes) {
  if (elem_size_bytes != 1) {
    std::stringstream ss;
    ss << __FUNCTION__;
    ss << ": only torch::kUInt8 data type is supported";
    throw std::runtime_error(ss.str());
  }

  auto options = torch::TensorOptions()
                     .dtype(torch::kUInt8)
                     .layout(torch::kStrided)
                     .device(torch::kCUDA);

  torch::Tensor tensor = torch::full({height, width}, 128, options);

  uint8_t *devMem = tensor.data_ptr<uint8_t>();
  if (!devMem) {
    std::stringstream ss;
    ss << __FUNCTION__;
    ss << ": Pytorch tensor doesn't have data ptr.";

    throw std::runtime_error(ss.str());
  }

  if (!ptr) {
    std::stringstream ss;
    ss << __FUNCTION__;
    ss << ": Video frame has void CUDA device ptr.";

    throw std::runtime_error(ss.str());
  }

  auto res = cudaMemcpy2D((void *)devMem, width, (const void *)ptr, pitch,
                          width, height, cudaMemcpyDeviceToDevice);
  if (cudaSuccess != res) {
    std::stringstream ss;
    ss << __FUNCTION__;
    ss << ": failed to copy data to tensor. CUDA error code: ";
    ss << res;

    throw std::runtime_error(ss.str());
  }

  return tensor;
}

int main(int argc, const char **argv) {
  if (argc < 4) {
    cerr << "Provide gpu ID, path to input and output files" << endl;
    return 1;
  } else {
    cout << "This sample decodes input video to raw NV12 file on given GPU."
         << endl;
    cout << "Usage: SampleDecode $gpu_id $input_file $output_file." << endl;
  }

  // GPU ID;
  stringstream ss;
  ss << argv[1];
  int gpu_id = -1;
  ss >> gpu_id;

  // Input file;
  string input(argv[2]);

  // Output file;
  string output(argv[3]);
  ofstream fout(output, std::ios::binary);

  PyNvDecoder nvDec(input, gpu_id);
  // Native Nvdec output format is NV12;
  // First we convert it to RGB and then to RGB planar for export to Pytorch tensor;
  PySurfaceConverter nv12_rgb(nvDec.Width(), nvDec.Heigth(), NV12, RGB, gpu_id);
  PySurfaceConverter rgb_planar(nvDec.Width(), nvDec.Heigth(), RGB, RGB_PLANAR, gpu_id);

  do {
    auto nv12Surface = nvDec.DecodeSingleSurface();
    if (!nv12Surface) {
      break;
    } else {
      auto rgbSurface = nv12_rgb.Execute(nv12Surface);
      auto rgbPlanar = rgb_planar.Execute(rgbSurface);

      auto pPlane = rgbPlanar->PlanePtr();
      auto gpuMem = pPlane->GpuMem();
      auto tensor = makefromDevicePtrUint8(gpuMem, pPlane->Width(),
        pPlane->Height(), pPlane->Pitch(), pPlane->ElemSize());
    }
  } while (true);

  fout.close();
 return 0;
}

You can look at the PyNvCodec.cpp file to see actual C++ API of VPF classes.

--
BR, Roman Arzumanyan

**Comment by QuantScientist** [comment]
Thanks for your efforts. 
I am going to test it and report it back.
